export const PHOTO_GALLERY_ITEM = [
    {
        src:
            "/images/1.jpg",
    },
    {
        src:
            "/images/2.jpg",
    },
    {
        src:
            "/images/3.jpg",
    },
    {
        src:
            "/images/4.jpg",
    },
    {
        src:
            "/images/5.png",
    },
    {
        src:
            "/images/6.jpg",
    },
    {
        src:
            "/images/7.jpg",
    },
    {
        src:
            "/images/8.jpg",
    },
];